language: python
cache: pip
sudo: false

python:
  - 2.7
  - 3.5
env:
  - PANDAS_VERSION=0.18.1
    NUMPY_VERSION=1.11.1
  - PANDAS_VERSION=0.22.0
    NUMPY_VERSION=1.14.1

before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:
  - conda create -n testenv --yes -c quantopian pip python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION pandas=$PANDAS_VERSION
  - source activate testenv
  - python -m pip install --upgrade pip coveralls
  - python -m pip install -r etc/requirements.txt
  - python -m pip freeze | sort

script:
  - flake8 trading_calendars tests
  - nosetests tests

after_success:
  - coveralls

notifications:
  email: false

branches:
  only:
    - master
